version: '3.4'

services:
  myapp:
    image: ${DOCKER_REGISTRY-}myapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings=Server= HOME-PC ;Database= lab3 ;User Id= user ;Password= 12345 ;TrustServerCertificate= True;
    ports:
      - "5000:5000"
    depens_on:
      - db
  db:
   image: "mcr.microsoft.com/mysql/server"
   environment:
     - "SA_PASSWORD = 12345"
     - "ACCEPT_EULA = Y"
    conteiner_name: mysql